#! /bin/sh

# Monitor settings
bspc monitor DP-0 -d 1 2 3 4 5 6
bspc monitor HDMI-0 -d 7 8 9

# Window settings
bspc config border_width 0
bspc config window_gap 0
bspc config bottom_padding 27
bspc config split_ratio 0.50

# Window rules
bspc rule -a '*' monitor=DP-0
bspc rule -a Firefox desktop=^1
bspc rule -a discord desktop=^7
bspc rule -a obs desktop=^8
bspc rule -a Flashplayer state=tiled

## ENV
# QT Theme
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_STYLE_OVERRIDE=kvantum

## Startup
# Keybinds
sxhkd &

# Bar
~/.config/polybar/launch.sh

# Wallpaper
feh --bg-scale ~/Pictures/Wallpapers/Wallpaper.jpg

# Disable CapsLock
xmodmap ~/.Xmodmap

# Compositor
compton -b

# Fix Cusor
xsetroot -cursor_name left_ptr

# Notifications
dunst &

# Keyboard Colors/Macros
g910-led -a 0000FF
g910-led -gkm 1

# Programs
discord &
