#! /bin/sh

sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5 6
bspc monitor HDMI-0 -d 7 8 9

bspc config border_width 0
bspc config window_gap 0
bspc config bottom_padding 27

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a '*' monitor=DP-0
bspc rule -a Firefox desktop=^1
bspc rule -a discord desktop=^7
bspc rule -a obs desktop=^8
bspc rule -a termite:floating state=floating
bspc rule -a Flashplayer state=tiled

discord &
~/.config/polybar/launch.sh
