#!/bin/bash

# Monitor settings
bspc monitor DP-2   -d 1 2 3
bspc monitor DP-0   -d 4 5 6
bspc monitor HDMI-0 -d 7 8 9

# Window settings
bspc config border_width 0
bspc config window_gap 0
bspc config bottom_padding 27
bspc config split_ratio 0.50
#bspc config normal_border_color "#4a4a4a"
#bspc config focused_border_color "#bcecff"

# Window rules
bspc rule -a '*'         monitor=DP-0
bspc rule -a firefox     monitor=DP-0
bspc rule -a discord     monitor=DP-2
bspc rule -a obs         monitor=HDMI-0
bspc rule -a flashplayer state=tiled
bspc rule -a yakuake     state=floating

## Startup

# Hotkey Daemon
sxhkd &

# Disable CapsLock
xmodmap ~/.Xmodmap

# Fix Cusor On Desktop
xsetroot -cursor_name left_ptr

# Keyboard Colors/Macros
g910-led -a 00FFFF
g910-led -gkm 1

# Bar
~/.config/polybar/launch.sh

# Wallpaper
feh --bg-scale Pictures/Wallpapers/Misc/Flower.jpg

# Compositor
compton -b

# Notifications
dunst &

# Programs
discord-canary &
yakuake &
